language: python
python:
- '3.3'
- '3.4'
- '3.5'
- '3.6'
# branches:
#   only:
#   - master
before_install:
- cd tests
- openssl aes-256-cbc -K $encrypted_758739719b2f_key -iv $encrypted_758739719b2f_iv
  -in secrets.tar.enc -out secrets.tar -d
- tar xvf secrets.tar
install:
- pip install -r requirements.txt
script:
- py.test
# after_success:
# - coveralls
# notifications:
#   slack:
#     secure: JAtGb4AZhSvR+xu/Vx9sLBBctJPzI+QFFMbz4NjJ8DQNZTZsPMeJrXZeivJK+ZqH9fhyGIB9Tf3B3EI9zkrKb6GRytRfy1pg2S+GCdhfBRYiJpvy15xMih+ljTsbH01XL1rzhkTu4Kizy8UHLTMDkDuIKznalhsBj+3zhtsmwl68ZCAJdwDEfd756lqSP4Un4iXnr5xy2L6ht5635aT1O1DvhtQeVSu9D11wpBBY1P5FSaeFWOL4Sfmb3FgNMbX6GfWTJtoN7MGhi2IxzLJJUfxiYzO5MXfHBidF74dFvFr8kYgjFQ1cDbwmMPOVCwJbZshAbjf2VRfHizUWc3kuKO3YDoevU/oAiNLkoRpql34wDNh1A0He9/K8/XwGJdEIvUkKBZeSci0jbxkcajnr2pe+pC7SEXFa5r9aA8JRw7JclM6VVdKysLPwuaUKKtNF6Yf4OW9/BSvBfU/LQ3YRh2aJV8PBo5RRjRsS4k2KVVvE/yO1W5AHWaFCiaXXIsg0R5ndJjqh+e3fXNG1PC52Ck4CSzEbdzAi8Z2UYlhLyDvQaeIc2jz/OE0noU+92J0DpEaLbr/j1mo+tbCieE6Q3Va0LnjkNJ/wYU5Ttl2xNHe3QU+ymAFuTHzXXrLLWlM+4iev6KZn2P1jkQBHY45DIU232UzGrCIDq++1elwxUIs=
